### ISSUE TITLE
Light part of icons should not be transparent

### ISSUE THREAD

**Issue by math1985** [nebulon42/osmic#10]
I don't think transparency works well for the inner parts of icons. In particular for amenity=bank it is problematic. See for example [here](http://www.openstreetmap.org/?mlat=49.61235&mlon=6.12888#map=17/49.61235/6.12888), where the footway is visible through the white part of the bank note. I think it would look better if this was rendered white or gray. Perhaps that requires a three-colour model for the SVG files - dark, light, and transparent?

**Comment by nebulon42** [comment]
I see the problem. My initial attempt at it was to keep inner holes as small as possible, that is why I'm not too happy about the cinema icon. But this was not always possible due to readability and wishes in the comments.

There is nothing that stops us from using three colours but `marker-fill`. Of course, every fill will be changed to the colour specified there. Another possibility is using transparency, but again the colour will be the same.

This is partly similar to #3, where I think that we will need halos for improved legibility on noisy backgrounds.

**Comment by math1985** [comment]
> Of course, every fill will be changed to the colour specified there.

True, so I think there's not much we can do about it. Closing this issue.

**Comment by nebulon42** [comment]
I will still have a test run regarding transparency.

**Comment by nebulon42** [comment]
Reopening, otherwise I will forget about the test run.

**Comment by nebulon42** [comment]
Related to #3.

**Comment by nebulon42** [comment]
This might have been fixed by https://github.com/nebulon42/osmic/commit/135010e64ff3a9e3ce067519da91ee02482eea6a, but further investigation is necessary.

**Comment by nebulon42** [comment]
Conclusion: There should not be large inner holes.
